imageToText: |
  Extract the questions from this image. 
  However, here are some additional rules.
  - If there is mathematical notation, then write the question in katex.
  - If the question has an image or graph, skip the question and return ""
  - If the question requires tables, figures or drawings then skip them
generateQans: |
  # Generate the questions, answers, notes and solutions from the text above.
  Analyze the math questions above and then for each:

  1. Reword the question and change the numbers used  to avoid intellectual property issues, but preserve the spirit of the original question.
  2. Make sure your question doesn't include tables, graphs or diagrams of any kind.
  3. Answer the following:
  - What key concepts and principles are being assessed in this question? (e.g., algebra, geometry, trigonometry, calculus)
  - What are the steps involved in solving this problem effectively? Demonstrate while solving the problem. Show all working. Do not skip any steps. I repeat, show *all* of your working.
  - If applicable, explain the reasoning behind using a specific mathematical operation or formula in each step.
  - Are there any common misconceptions or pitfalls students should be aware of when answering this type of question? (e.g., order of operations, incorrect application of formulas, sign errors)

  - Also abide by the following editing notes
editingNotes: |
  - Escape \ in KaTeX syntax to prevent errors in JSON. For example, [tex]\frac{31}{10}[/tex] should become [tex]\\frac{31}{10}[/tex]
  
  - For equations that should be displayed on their own line, use [texd] instead of [tex] and wrap in equation environments:
    - Single line: [texd]\\begin{equation*} x + y = 5 \\end{equation*}[/texd]
    - Multiple lines: [texd]\\begin{equation*} \\begin{split} x + y &= 5 \\ y &= 5 - x \\end{split} \\end{equation*}[/texd]
    - Use & before = signs to align equations
    - Use \\ for line breaks in multi-line equations
  
  - Keep inline equations (within text) using [tex] without environments
  - If a "section" property, for example, `"section": 9` is present, return it as is
  - Ensure that the answer is correct and matches the solution provided.
  - For money within katex, use \\$ instead of $. Outside of katex, use $ for money.
  - For vectors, use \overrightarrow instead of \vec.
  
  1. Write for a grade-6 reading level.
  
  2. Make the tone conversational. For example:
      - "In step 2, we use the distributive property because..."
      - "The reason we use the Pythagorean theorem here is because..."
  
  3. All answers must be of type 'string'.
  
  4. All values must be in valid HTML syntax.
  
  5. For all mathematical steps (including in the new question, answer, solution, and notes), follow these instructions:
      - Use a separate line for each mathematical step.
      - Enclose inline math in [tex] tags and display math in [texd] tags
      - Use valid KaTeX notation for all expressions
      - Use proper equation environments for display math
      - If you need to write an exponent, use KaTeX's `^` for exponents
      - Fractions should be written as `\\frac{a}{b}`
  
  6. Round all decimals to 2 decimal places and indicate the same.
  
  7. Present your response in a JSON object with the following keys:
      - `question` (string): The new question.
      - `answer` (string): The single answer to the question (no explanation needed).
      - `solution` (string): The step-by-step working that demonstrates how you arrived at the answer.
      - `notes` (string): Include helpful information for students in preparing for similar questions.
  
  8. For the notes section, follow these rules:
      - Ensure all sections are numbered in ordered lists
      - Convert all mathematical expressions to valid KaTeX with appropriate inline/display mode
  
  9. For the `solutions` and `notes` sections:
      - Avoid using section headers like `<h3>Solution</h3>` or `<h3>Notes</h3>`
      - Follow HTML guidelines for formatting
      - Ensure consistent formatting across sections
      - Return response as valid JSON
      - Don't use diagrams, images, tables, or graphs
classify: |
  Analyze these questions, and classify them using the following sections.
  Add the key to each question in a new 'section' field with the number of the section.
doubleCheck: |
  Review the following objects and ensure that the question, answer, solution, and notes for each meet the following criteria:
    Fix KaTeX syntax in the following JSON using these rules:

    - All math expressions must be wrapped in [tex]...[/tex] tags
    - Text in math mode should use \\text{}: [tex]\\text{where } x > 0[/tex]

    Additional requirements:
    - Preserve all HTML formatting and structure
    - Do not remove any fields or content
    - Only fix KaTeX syntax issues
    - Provide no explanation - only the corrected JSON
    - I don't want to see any corrections midway through the solutions or notes (like `Oops! I made a mistake earlier.`). Just give me the correct response.
marketing:
  quizzes: |
    Based on the following sections of a syllabus, create 5 short
    quizzes with multiple choice answers. Each quiz should be no more 
    than 30 words. The questions should be at a grade 7-9 level of 
    difficulty. Return the quizzes as an array of objects in valid json syntax.
    Dont' assign the array to a variable. Just give me the array. 
    Each question should have no more than 3 options. 

    The format of the object should be:
    { question: string, optionA: string, optionB: string, optionC: string }

    Here are the sections:
      - Number Theory and Computation
      - Consumer Arithmetic
      - Measurement
      - Statistics
      - Algebra

    Here are sample quizzes:
    [
      {
        question: 'What is 2.75 expressed as a fraction in its simplest form?',
        optionA: '11/4',  // Correct
        optionB: '7/2',
        optionC: '275/100'
      },
      {
        question: 'If a shirt costs $40 and is on sale for 25% off, what is the final price?',
        optionA: '$30',  // Correct
        optionB: '$35',
        optionC: '$25'
      },
      {
        question: 'A rectangular garden has length 8m and width 6m. What is its area?',
        optionA: '14m²',
        optionB: '28m²',
        optionC: '48m²'  // Correct
      },
      {
        question: 'What is the mean of the numbers: 3, 7, 8, 12, 15?',
        optionA: '7',
        optionB: '8',
        optionC: '9'  // Correct
      },
      {
        question: 'Solve for x: 3x + 5 = 20',
        optionA: 'x = 5',  // Correct
        optionB: 'x = 6',
        optionC: 'x = 7'
      }
    ];
  examPrepTips: |
    Give me some exam preparation tips in an array
    of strings. The array should be in valid json syntax.
    This is for students in grades 9-12. 
    The reading level should be for grade 6. 
    Each tip should be no more than 50 words.
    Dont' assign the array to a variable. Just give me the array.
  motivation: |
    Give me 10 motivational quotes and provide attribution. 
    Give them to me in an array of strings. 
    The array must be in valid JSON syntax.
    Dont' assign the array to a variable. Just give me the array. 
    They aren't limited to math. 
    Provide attribution in the same string, but separated by a newline. 
    Ensure the quote is wrapped in quotation marks, Like so:
    ```
    '"Quote"

    - Author
    '
    ```
expandSolution: |
  For each of the questions above, re-write the solution in a way that abides by the following rules:
  Write the solutions as if you're explaining the concept to a learner in a friendly, conversational way. 
  Imagine you're walking them through the steps, step-by-step, in a tone similar to Sal Khan from Khan Academy. 
  Be approachable, brief, and guide them as if you're teaching the concept during a tutoring session.
  Each step will be eventually converted to a photo, so make sure that each step in the solution is less than 60 words.
  Each step should begin with an <h3> tag. Each heading should begin with the numbered step, for example <h3>Step 1: ...</h3>. All math should abide by the KaTeX syntax outlined in the editing notes.
  Each advancement in the solution should be a new line.
  Return each question with all of its original fields, including the solution and section. Leave the other fields unchanged. However, the solution should be re-written to abide by the rules above.
  Ensure that the solution is consistent with the answer and the notes.
  Return the response as valid JSON.
  Don't include greetings like "Hey there!" or "Let's get started!" in the solution.
  Each line of the solution should be no more than 40 characters long. If it is longer, break it up into multiple lines within multiple <p> tags.
  Ensure that each sentence in the solution is started on a new line, so use a <p> tag for each sentence.
  Ensure that the solution abides by the following editing notes:
correctness: |
  Review each object for the accuracy of the answer to the question. 
  Then, review each object for consistency between the answer and the solution in substance not style. 
  If the answer is correct and consistent with the solution, then return the question prepended by the ✅ emoji. 
  If there are errors or inconsistencies between the answer and the solution, return question prepended by the ❌ emoji and the corrections in "corrections" in a JSON object. 
  Spend no more than 1 minute thinking about each question.

  Here are the questions:
displayMode: |
  Please modify the math expressions in these questions according to these rules:

  1. For any multi-line equations or equations that should be displayed on their own line:
    - Replace [tex] with [texd]
    - Wrap the equation in \begin{equation} and \end{equation}
    - For equations with multiple lines:
      - Add \\begin{split} and \\end{split} inside the equation environment
      - Place & before = signs to align them
      - Use \\ for line breaks

  2. Keep inline equations (within text) using [tex] without any additional environments.

  3. Examples:
    Single line display equation:
    [texd]\\begin{equation} x + y = 5 \\end{equation}[/texd]

    Multi-line display equation:
    [texd]\\begin{equation} \\begin{split}
    x + y &= 5 \\
    y &= 5 - x
    \\end{split} \\end{equation}[/texd]

    Inline equation:
    The value of [tex]x[/tex] is 5.

  Please maintain all other formatting and content exactly as is.
  If a "section" property, for example, `"section": 9` is present, return it as is