imageToText: |
  Extract the questions from this image. 
  However, here are some additional rules.
  - If there is mathematical notation, then write the question in katex.
  - If the question has an image or graph, skip the question and return ""
  - If the question requires tables, figures or drawings then skip them
generateQans: |
  # Generate the questions, answers, notes and solutions from the text above.
  Analyze the math questions above and then for each:

  1. Reword the question and change the numbers used  to avoid intellectual property issues, but preserve the spirit of the original question.
  2. Make sure your question doesn't include tables, graphs or diagrams of any kind.
  3. Answer the following:
  - What key concepts and principles are being assessed in this question? (e.g., algebra, geometry, trigonometry, calculus)
  - What are the steps involved in solving this problem effectively? Demonstrate while solving the problem. Show all working. Do not skip any steps. I repeat, show *all* of your working.
  - If applicable, explain the reasoning behind using a specific mathematical operation or formula in each step.
  - Are there any common misconceptions or pitfalls students should be aware of when answering this type of question? (e.g., order of operations, incorrect application of formulas, sign errors)

  - Also abide by the following editing notes
editingNotes: |
  - Escape \ in KaTeX syntax to prevent errors in JSON. For example, [tex]\frac{31}{10}[/tex] should become [tex]\\frac{31}{10}[/tex] and <p>[tex]4\frac{2}{5} = \frac{(4 \times 5) + 2}{5} = \frac{22}{5}[/tex]</p> should become <p>[tex]4\\frac{2}{5} = \\frac{(4 \\times 5) + 2}{5} = \\frac{22}{5}[/tex]</p>
  - Ensure that the answer is correct and matches the solution provided.
  - For vectors, use \overrightarrow instead of \vec.
  1. Write for a grade-6 reading level.
  2. Make the tone conversational. For example:
      - "In step 2, we use the distributive property because..."
      - "The reason we use the Pythagorean theorem here is because..."
  3. All answers must be of type ‘string’.
  4. All values must be in valid HTML syntax.
  5. For all mathematical steps (including in the new question, answer, solution, and notes), follow these instructions:
      - Use a separate line for each mathematical step.
      - Enclose every mathematical expression in `[tex]` and `[/tex]` tags for proper rendering.
      - Use valid KaTeX notation for all expressions (e.g., no exponential notation like `^2` or fractions like `a/b` unless converted to KaTeX).
      - If you need to write an exponent, use KaTeX's `^` for exponents (e.g., `x^2`), and fractions should be written as `\frac{a}{b}`.
  6. Round all decimals to 2 decimal places and indicate the same.
  7. Present your response in a JSON object with the following keys:
      - `question` (string): The new question.
      - `answer` (string): The single answer to the question (no explanation needed).
      - `solution` (string): The step-by-step working that demonstrates how you arrived at the answer.
      - `notes` (string): Include helpful information for students in preparing for similar questions.
  8. For the notes section, follow these rules:
      - Add the Unicode bullet point symbol  before each `<li>` in unordered list items in the `notes` section.
      - Ensure all sections are numbered in ordered lists (e.g., "1. First point").
      - Do not use exponential notation (`^2`) or fractions like `a/b` in the text. Convert all mathematical expressions to valid KaTeX.
  9. For the `solutions` and `notes` sections:
      - Avoid using section headers like `<h3>Solution</h3>` or `<h3>Notes</h3>`.
      - Follow these HTML guidelines for formatting:
          - Use `<h3>` for main sections.
          - Use `<h4>` only if absolutely necessary (keep the hierarchy flat).
          - Keep paragraphs brief and use `<p>` tags.
          - Use ordered lists (`<ol>`) for steps and unordered lists (`<ul>`) for bullet points.
          - Use `<strong>` for emphasis on important words/phrases and `<em>` for regular emphasis.
          - Ensure that mathematical expressions are in KaTeX format inside `[tex]` and `[/tex]` tags.
          - Use `<br>` sparingly, only for line breaks within paragraphs or code blocks.
          - Ensure links are descriptive if used within the solution or notes.
      - Follow consistent formatting across all sections. Avoid excessive nesting; maintain clarity and readability.
      - Return the response as valid JSON.
      - Don't use diagrams, images, tables, or graphs in the solution.
classify: |
  Analyze these questions, and classify them using the following sections.
  Add the key to each question in a new 'section' field with the number of the section.
doubleCheck: |
  Review the following objects and ensure that the question, answer, solution, and notes for each meet the following criteria:
    Fix KaTeX syntax in the following JSON using these rules:

    - All math expressions must be wrapped in [tex]...[/tex] tags
    - Text in math mode should use \\text{}: [tex]\\text{where } x > 0[/tex]

    Additional requirements:
    - Preserve all HTML formatting and structure
    - Do not remove any fields or content
    - Only fix KaTeX syntax issues
    - Provide no explanation - only the corrected JSON
marketing:
  quizzes: |
    Based on the following sections of a syllabus, create 5 short
    quizzes with multiple choice answers. Each quiz should be no more 
    than 30 words. The questions should be at a grade 7-9 level of 
    difficulty. Return the quizzes as an array of objects in valid json syntax.
    Dont' assign the array to a variable. Just give me the array. 
    Each question should have no more than 3 options. 

    The format of the object should be:
    { question: string, optionA: string, optionB: string, optionC: string }

    Here are the sections:
      - Number Theory and Computation
      - Consumer Arithmetic
      - Measurement
      - Statistics
      - Algebra

    Here are sample quizzes:
    [
      {
        question: 'What is 2.75 expressed as a fraction in its simplest form?',
        optionA: '11/4',  // Correct
        optionB: '7/2',
        optionC: '275/100'
      },
      {
        question: 'If a shirt costs $40 and is on sale for 25% off, what is the final price?',
        optionA: '$30',  // Correct
        optionB: '$35',
        optionC: '$25'
      },
      {
        question: 'A rectangular garden has length 8m and width 6m. What is its area?',
        optionA: '14m²',
        optionB: '28m²',
        optionC: '48m²'  // Correct
      },
      {
        question: 'What is the mean of the numbers: 3, 7, 8, 12, 15?',
        optionA: '7',
        optionB: '8',
        optionC: '9'  // Correct
      },
      {
        question: 'Solve for x: 3x + 5 = 20',
        optionA: 'x = 5',  // Correct
        optionB: 'x = 6',
        optionC: 'x = 7'
      }
    ];
  examPrepTips: |
      Give me some exam preparation tips in an array
      of strings. The array should be in valid json syntax.
      This is for students in grades 9-12. 
      The reading level should be for grade 6. 
      Each tip should be no more than 50 words.
      Dont' assign the array to a variable. Just give me the array. 
  motivation: |
    Give me 10 motivational quotes and provide attribution. 
    Give them to me in an array of strings. 
    The array must be in valid JSON syntax.
    Dont' assign the array to a variable. Just give me the array. 
    They aren't limited to math. 
    Provide attribution in the same string, but separated by a newline. 
    Ensure the quote is wrapped in quotation marks, Like so:
    ```
    '"Quote"

    - Author
    '
    ```